#pragma config(Sensor, in1,    lineTrackerLeft, sensorLineFollower)
#pragma config(Sensor, in2,    lineTrackerRight, sensorLineFollower)
#pragma config(Sensor, in3,    lineTrackerCenter, sensorLineFollower)
#pragma config(Sensor, dgtl1,  leftBumpSwitch, sensorTouch)
#pragma config(Sensor, dgtl2,  rightBumpSwitch, sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           armMotor,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define motorFAST 100
#define motorMEDIUM 60
#define motorSLOW 40

void lineTracker();
void turnLeft(int speed);
void turnRight(int speed);
void moveForward(int speed);
void moveBackward(int speed);
void stopMotor();
void grabObject();
void armClose();
void armOpen();
void turnRightJunctionOne();
void turnLeftJunctionTwo();
void moveArmMotor(int time, int speed);
void lineTracker_grabObject();
void lineBackTracker();
void turnLeftBack(int speed);
void turnRightBack(int speed);
void turnRightJunction(int speed);
void turnRightBackJunction();
void turnLeftJunctionBack();

task main()
{
	  int state = 40;

	  //allow us to position robot down properly
	  wait1Msec(2000);

	  while(1) {
			switch (state) {

				case(0):
				break;

			  //state 1: line following from start to T junction
			  case (1):
			  lineTracker();
			  state++;
			  break;

	  		case (2):
	  		moveBackward(motorMEDIUM);
	  		wait1Msec(500);
	  		turnRightJunctionOne();
	  		state++;
	  		break;

	  		// state 3: line following from T junction 1 to T junction 2
	  		case (3):
	  		lineTracker();
	  		state++;
	  		break;

	  		// state 4: turn left at junction t
	  		case (4):
	  		turnLeftJunctionTwo();
	  		state++;
	  		break;





	  		// ARM MECHANISM
	  		// state 5: line follow until hit object
	  	  case (5):
	  	  lineTracker_grabObject();
	  	  state++;
	  	  break;

	  	  case(6):
	  	  moveBackward(80);
	  	  wait1Msec(300);
	  	  grabObject();
	  	  state = 69;
	  	  break;




	  	  //traveling backwards

	  	  case (69):
	  	  lineBackTracker();
	  	  state++;
	  	  break;

	  	  case(70):
	  	  turnRightBackJunction();
	  	  state++;
	  	  break;

	  	  //following line until T junction
	  	  case(71):
	  	  lineBackTracker();
	  	  state++;
	  	  break;

	  	  //turning at T junction
	  	  case(72):
	  	  turnLeftJunctionBack();
	  	  state = 40;
	  	  break;





	  	  //final stage

	  	  // state 1 to junction 1
	  	  case(40):
	  	  lineTracker();
	  	  state++;

	  	  //go forward tor a few seconds
	  	  case(41):
	  	  moveForward(80);
	  	  wait1Msec(300);
	  	  stopMotor();
	  	  state++;
	  	  break;

	  	  // junction 1 to star junction
	  	  case(42):
	  	  lineTracker();
	  	  state++;
	  	  break;

				// go forward blindly for a bit
	  	  case(43):
	  	  moveForward(80);
	  	  wait1Msec(300);
	  	  stopMotor();
	  	  state++;
	  	  break;

	  	  // reach box A
	  	  case (44):
	  	  lineTracker();
	  	  state++;
	  	  break;

	  	  //place object down in box A
	  	  case (45):
	  	  armOpen();
	  	  state=0;
	  	  break;
	  	}
	 }
}

void lineTracker()
{

  //Create and set the threshold for the Line Tracking Sensors.
  int threshold = 2000;

  // sensor values for debugging purposes
  int leftLineSensor;
	int rightLineSensor;
	int centerLineSensor;

  while(1)
  {
    leftLineSensor = SensorValue(lineTrackerLeft);
    rightLineSensor = SensorValue(lineTrackerRight);
    centerLineSensor = SensorValue(lineTrackerCenter);

    if ( ((leftLineSensor > threshold) && (centerLineSensor > threshold)) ||\
    		 ((rightLineSensor > threshold) && (centerLineSensor > threshold)) ||\
    	   ((rightLineSensor > threshold) && (centerLineSensor > threshold) && (leftLineSensor > threshold)) ||\
    	   ((rightLineSensor > threshold) && (leftLineSensor > threshold)) )
    {
       stopMotor();
       wait1Msec(3000);
       return;
    }

    //If the center sensor sees dark...
    if (SensorValue(lineTrackerCenter) > threshold) {
    	 moveForward(motorMEDIUM);
    }

    //If the left sensor sees dark...
  	else if(SensorValue(lineTrackerLeft) > threshold) {
			 while (SensorValue(lineTrackerCenter) < threshold) {
  		    turnLeft(motorFAST);
    	    wait1Msec(15);
     	    moveForward(motorMEDIUM);
     	    wait1Msec(5);

    if ( ((leftLineSensor > threshold) && (centerLineSensor > threshold)) ||\
    		 ((rightLineSensor > threshold) && (centerLineSensor > threshold)) ||\
    	   ((rightLineSensor > threshold) && (centerLineSensor > threshold) && (leftLineSensor > threshold)) ||\
    	   ((rightLineSensor > threshold) && (leftLineSensor > threshold)) )
        {
           stopMotor();
           wait1Msec(3000);
           return;
        }

     }
   }

    //If the right sensor sees dark...
    else if(SensorValue(lineTrackerRight) > threshold) {
       while (SensorValue(lineTrackerCenter) < threshold) {
    	 	  turnRight(motorFAST);
     	    wait1Msec(15);
     	    moveForward(motorMEDIUM);
     	    wait1Msec(5);

        if ( ((leftLineSensor > threshold) && (centerLineSensor > threshold)) ||\
    		     ((rightLineSensor > threshold) && (centerLineSensor > threshold)) ||\
    	       ((rightLineSensor > threshold) && (centerLineSensor > threshold) && (leftLineSensor > threshold)) ||\
    	       ((rightLineSensor > threshold) && (leftLineSensor > threshold)) )
        {
        stopMotor();
        wait1Msec(3000);
        return;
        }
       }
    }

  	else {
  		moveForward(motorMEDIUM);
    }
   }  //for while loop
}

void lineTracker_grabObject()
{

  //Create and set the threshold for the Line Tracking Sensors.
  int threshold = 2500;

  // sensor values for debugging purposes
  int leftLineSensor;
	int rightLineSensor;
	int centerLineSensor;

  while(1)
  {
    leftLineSensor = SensorValue(lineTrackerLeft);
    rightLineSensor = SensorValue(lineTrackerRight);
    centerLineSensor = SensorValue(lineTrackerCenter);

    if ( (SensorValue(leftBumpSwitch) == 1) && (SensorValue(rightBumpSwitch) == 1) )
    {
    	stopMotor();
       wait1Msec(3000);
       return;
     }

    //If the center sensor sees dark...
    if (SensorValue(lineTrackerCenter) > threshold) {
    	 moveForward(motorMEDIUM);
    }

    //If the left sensor sees dark...
  	else if(SensorValue(lineTrackerLeft) > threshold) {
			 while (SensorValue(lineTrackerCenter) < threshold) {
  		    turnLeft(motorFAST);
    	    wait1Msec(15);
     	    moveForward(motorMEDIUM);
     	    wait1Msec(5);

    if ( (SensorValue(leftBumpSwitch) == 1) && (SensorValue(rightBumpSwitch) == 1) )
    {
    	stopMotor();
       wait1Msec(3000);
       return;
     }

       }
    }

    //If the right sensor sees dark...
    else if(SensorValue(lineTrackerRight) > threshold) {
       while (SensorValue(lineTrackerCenter) < threshold) {
    	 	  turnRight(motorFAST);
     	    wait1Msec(15);
     	    moveForward(motorMEDIUM);
     	    wait1Msec(5);

    if ( (SensorValue(leftBumpSwitch) == 1) && (SensorValue(rightBumpSwitch) == 1) )
    {
    	stopMotor();
       wait1Msec(3000);
       return;
     }

       }
    }

  	else {
  		moveForward(motorMEDIUM);
    }
   }
}

void moveForward(int speed)
{
	 motor[leftMotor] = speed * -1;
	 motor[rightMotor] = speed;
}

void moveBackward(int speed)
{
	 motor[leftMotor] = speed;
	 motor[rightMotor] = speed * -1;
}

void turnLeft(int speed)
{
	 motor[leftMotor] = 0;
	 motor[rightMotor] = speed;
}

void turnRight(int speed)
{
	 motor[leftMotor] = speed * -1;
	 motor[rightMotor] = 0;
}

void turnRightJunction(int speed)
{
	 motor[leftMotor] = speed * -1;
	 motor[rightMotor] = speed * -1;
}
void stopMotor()
{
	 motor[leftMotor] = 0;
	 motor[rightMotor] = 0;
}

void turnRightJunctionOne()
{
				turnRight(110
				);
	  	  wait1Msec(1500);

	  		while (SensorValue(lineTrackerRight) < 2000)
	  		{

	  			//turnRight(motorMEDIUM);
	  			//wait1Msec(500);
     	    //moveForward(motorMEDIUM);
     	    //wait1Msec(200);
	  		motor[leftMotor] = -100;
	 motor[rightMotor] = 50;
     	  }

	  		stopMotor();
	  		wait1Msec(2000);
}

void turnLeftJunctionTwo()
{
				moveBackward(motorMEDIUM);
	  		wait1Msec(1000);

	  		while (SensorValue(lineTrackerRight) < 2500)
	  		{
	  		//moveBackward(motorMEDIUM);
	  			turnLeft(motorMEDIUM);
	  			wait1Msec(500);
     	    moveForward(motorMEDIUM);
     	    wait1Msec(5);
     	  }

	  		stopMotor();
	  		wait1Msec(2000);
}

void grabObject()
{
		armClose();
}

void armClose()
{
	moveArmMotor( 30, 70);  //Set motor to run 100 counts at power level 75.    //arguments are motor, time(miliseconds), speed(127 max)
}

void armOpen()
{
	moveArmMotor( 30, -70);  //Set motor to run 100 counts at power level 75.    //arguments are time(miliseconds), speed(127 max)
}

void moveArmMotor(int time, int speed)
{
	motor[armMotor] = speed;
  wait1Msec(time);
  motor[armMotor] = 0;
}

void turnLeftBack(int speed)
{
	 motor[leftMotor] = 0;
	 motor[rightMotor] = speed * -1;
}

void turnRightBack(int speed)
{
	 motor[leftMotor] = speed;
	 motor[rightMotor] = 0;
}

void lineBackTracker()
{

  //Create and set the threshold for the Line Tracking Sensors.
  int threshold = 2500;

  // sensor values for debugging purposes
  int leftLineSensor;
	int rightLineSensor;
	int centerLineSensor;

  while(1)
  {
    leftLineSensor = SensorValue(lineTrackerLeft);
    rightLineSensor = SensorValue(lineTrackerRight);
    centerLineSensor = SensorValue(lineTrackerCenter);

    if ( ((leftLineSensor > threshold) && (centerLineSensor > threshold)) ||\
    		 ((rightLineSensor > threshold) && (centerLineSensor > threshold)) ||\
    	   ((rightLineSensor > threshold) && (centerLineSensor > threshold) && (leftLineSensor > threshold)) ||\
    	   ((rightLineSensor > threshold) && (leftLineSensor > threshold)) )
    {
       stopMotor();
       wait1Msec(3000);
       return;
    }

    //If the center sensor sees dark...
    if (SensorValue(lineTrackerCenter) > threshold) {
    	 moveBackward(motorMEDIUM);
    }

    //If the left sensor sees dark...
  	else if(SensorValue(lineTrackerLeft) > threshold) {
			 while (SensorValue(lineTrackerCenter) < threshold) {
  		    turnLeftBack(motorMEDIUM);
    	    wait1Msec(15);
     	    moveBackward(motorSLOW);
     	    wait1Msec(15);

    if ( ((leftLineSensor > threshold) && (centerLineSensor > threshold)) ||\
    		 ((rightLineSensor > threshold) && (centerLineSensor > threshold)) ||\
    	   ((rightLineSensor > threshold) && (centerLineSensor > threshold) && (leftLineSensor > threshold)) ||\
    	   ((rightLineSensor > threshold) && (leftLineSensor > threshold)) )
    {
       stopMotor();
       wait1Msec(3000);
       return;
    }

       }
    }

    //If the right sensor sees dark...
    else if(SensorValue(lineTrackerRight) > threshold) {
       while (SensorValue(lineTrackerCenter) < threshold) {
    	 	  turnRightBack(motorMEDIUM);
     	    wait1Msec(15);
     	    moveBackward(motorSLOW);
     	    wait1Msec(15);

    if ( ((leftLineSensor > threshold) && (centerLineSensor > threshold)) ||\
    		 ((rightLineSensor > threshold) && (centerLineSensor > threshold)) ||\
    	   ((rightLineSensor > threshold) && (centerLineSensor > threshold) && (leftLineSensor > threshold)) ||\
    	   ((rightLineSensor > threshold) && (leftLineSensor > threshold)) )
    {
       stopMotor();
       wait1Msec(3000);
       return;
    }

       }
    }

  	else {
  		moveBackward(motorMEDIUM);
    }
   }
}

void turnRightBackJunction()
{
	turnLeftBack(motorMEDIUM);
	 wait1Msec(300);
	 stopMotor();
}

void turnLeftJunctionBack()
{

	  		while (SensorValue(lineTrackerRight) < 2500)
	  		{
	  		//moveBackward(motorMEDIUM);
	  			turnLeft(motorMEDIUM);
	  			wait1Msec(500);
     	    moveForward(motorMEDIUM);
     	    wait1Msec(5);
     	  }

	  		stopMotor();
	  		wait1Msec(2000);
}
