#pragma config(Sensor, in1,    lineTrackerLeft, sensorLineFollower)
#pragma config(Sensor, in2,    lineTrackerRight, sensorLineFollower)
#pragma config(Sensor, in3,    lineTrackerCenter, sensorLineFollower)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define motorFAST 100
#define motorMEDIUM 75
#define motorSLOW 50

void lineTracker();
void turnLeft(int speed);
void turnRight(int speed);
void moveForward(int speed);

task main()
{
	  int state = 0;

	  while(1) {
			switch (state) {
				case(0):
				// do something here
				lineTracker();
			  break;
	  	}
	 }
}

void lineTracker()
{
  wait1Msec(500);

  //Create and set the threshold for the Line Tracking Sensors.
  int threshold = 1700;

  // sensor values for debugging purposes
  int leftLineSensor;
	int rightLineSensor;
	int centerLineSensor;

  while(1)
  {
    //If the left sensor sees dark...
  	leftLineSensor = SensorValue(lineTrackerLeft);
  	if(SensorValue(lineTrackerLeft) > threshold)
			 turnleft(motorSLOW);

    //If the center sensor sees dark...
    centerLineSensor = SensorValue(lineTrackerCenter);
    if(SensorValue(lineTrackerCenter) > threshold)
    	 moveForward(motorSLOW);

    //If the right sensor sees dark...
    rightLineSensor = SensorValue(lineTrackerRight);
    if(SensorValue(lineTrackerRight) > threshold)
       turnRight(motorSLOW);
  }
}

void moveForward(int speed)
{
	 motor[leftMotor] = speed;
	 motor[rightMotor] = speed;
}

void turnLeft(int speed)
{
	 motor[leftMotor] = 0;
	 motor[rightMotor] = speed;
}

void turnRight(int speed)
{
	 motor[leftMotor] = speed;
	 motor[rightMotor] = 0;
}
