#pragma config(Sensor, in1,    lineTrackerLeft, sensorLineFollower)
#pragma config(Sensor, in2,    lineTrackerRight, sensorLineFollower)
#pragma config(Sensor, in3,    lineTrackerCenter, sensorLineFollower)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define motorFAST 100
#define motorMEDIUM 60
#define motorSLOW 50

void lineTracker();
void turnLeft(int speed);
void turnRight(int speed);
void moveForward(int speed);
void moveBackward(int speed);

task main()
{
	  int state = 1;

	  //allow us to position robot down properly
	  wait1Msec(3000);

	  while(1) {
			switch (state) {

			  // testing moving mechanisms
				case(0):
				moveForward(motorFAST);
				wait1Msec(5000);

				moveForward(motorMEDIUM);
				wait1Msec(5000);

				moveForward(motorSLOW);
				wait1Msec(5000);

				turnLeft(motorFAST);
				wait1Msec(5000);

				turnLeft(motorMEDIUM);
				wait1Msec(5000);

				turnLeft(motorSLOW);
				wait1Msec(5000);

				turnRight(motorFAST);
				wait1Msec(5000);

				turnRight(motorMEDIUM);
				wait1Msec(5000);

				turnRight(motorSLOW);
				wait1Msec(5000);

				moveBackward(motorFAST);
				wait1Msec(5000);

				moveBackward(motorMEDIUM);
				wait1Msec(5000);

				moveBackward(motorSLOW);
				wait1Msec(5000);
			  break;


			  //case 1 tests line following
			  case (1):
			  lineTracker();
			  break;
	  	}
	 }
}

void lineTracker()
{

  //Create and set the threshold for the Line Tracking Sensors.
  int threshold = 2500;

  // sensor values for debugging purposes
  int leftLineSensor;
	int rightLineSensor;
	int centerLineSensor;

  while(1)
  {
    leftLineSensor = SensorValue(lineTrackerLeft);
    rightLineSensor = SensorValue(lineTrackerRight);
    centerLineSensor = SensorValue(lineTrackerCenter);

    //If the center sensor sees dark...
    if (SensorValue(lineTrackerCenter) > threshold) {
    	 moveForward(motorMEDIUM);
    }

    //If the left sensor sees dark...
  	else if(SensorValue(lineTrackerLeft) > threshold) {
			 while (SensorValue(lineTrackerCenter) < threshold) {
  		    turnLeft(motorFAST);
    	    wait1Msec(60);
     	    moveForward(motorMEDIUM);
     	    wait1Msec(5);
       }
    }

    //If the right sensor sees dark...
    else if(SensorValue(lineTrackerRight) > threshold) {
       while (SensorValue(lineTrackerCenter) < threshold) {
    	 	  turnRight(motorFAST);
     	    wait1Msec(60);
     	    moveForward(motorMEDIUM);
     	    wait1Msec(5);
       }
    }

  	else {
  		moveForward(motorMEDIUM);
    }
   }
}

void moveForward(int speed)
{
	 motor[leftMotor] = speed * -1;
	 motor[rightMotor] = speed;
}

void moveBackward(int speed)
{
	 motor[leftMotor] = speed;
	 motor[rightMotor] = speed * -1;
}

void turnLeft(int speed)
{
	 motor[leftMotor] = 0;
	 motor[rightMotor] = speed;
}

void turnRight(int speed)
{
	 motor[leftMotor] = speed * -1;
	 motor[rightMotor] = 0;
}
